### ISSUE TITLE
installer messiness

### ISSUE THREAD

**Issue by chrisdlangton** [mauro-balades/bash-plusplus#5]
I'd fix this but my `sed` with backslashes and variable-variables are beyond me
https://github.com/mauro-balades/bash-plusplus/blob/e0e5131a4e7cfdcb8230f57853e051969f3bbd4b/Makefile#L21

Just need to replace the value instead adding variable over-rides with every install forever

optionally also `sed` this with a `#` on uninstall?

**Comment by mauro-balades** [comment]
If we check the variable exists, we just add it. Wright?

**Comment by mauro-balades** [comment]
removed the makefile because I am remaking the project to a compiler. in https://github.com/mauro-balades/bash-plusplus/commit/f9cdaa1d9460350daa9e807a7598a621cd3da1d8
